# Generated by Django 5.1.5 on 2025-06-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
