# Generated by Django 5.1.5 on 2025-06-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
