# Generated by Django 5.1.5 on 2026-03-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_normalize_user_roles'),
        ('inventory', '0003_item_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('part_number', 'shop'), name='unique_part_number_per_shop'),
        ),
    ]
