# Generated by Django 5.1.5 on 2025-06-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_credit_receipt_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
