# Generated by Django 5.1.5 on 2025-06-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_customer_name_sale_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='receipt_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
