# Generated by Django 5.1.5 on 2025-06-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_receipt_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
