# Generated by Django 5.1.5 on 2025-07-08 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0005_credit_paid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sale_number', models.PositiveIntegerField(default=0)),
                ('last_credit_number', models.PositiveIntegerField(default=0)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.shop')),
            ],
        ),
    ]
