# Generated by Django 5.1.5 on 2026-03-06 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_normalize_user_roles'),
        ('inventory', '0003_item_part_number'),
        ('sales', '0006_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterShopCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_given', to='accounts.shop')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_shop_credits', to='inventory.item')),
                ('to_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_received', to='accounts.shop')),
            ],
        ),
        migrations.CreateModel(
            name='InterShopSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('item', 'Item')], default='cash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_made', to='accounts.shop')),
                ('settled_credits', models.ManyToManyField(blank=True, related_name='settlements', to='sales.intershopcredit')),
                ('to_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to='accounts.shop')),
            ],
        ),
    ]
