# Generated by Django 5.1.5 on 2026-03-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_receiptsequence'),
        ('sales', '0007_intershopcredit_intershopsettlement'),
    ]

    operations = [
    ]
